### PR TITLE
Add support for configuring Supervisor eventlisteners via buildout_init_commands

### PR DESCRIPTION
**Pull request by bryanlandia**

### CODE REVIEW

**Comment by bryanlandia** [comment]
Jumped the gun on this PR a little bit @alecpm ... didn't realize my memmon kept restarting.  Seeing if I've fixed it now.

**Comment by alecpm** [comment]
OK, just let me know when you have this sorted.  I was just thinking about adding this to the supervisor configs.

**Comment by bryanlandia** [comment]
OK, @alecpm it's working now.  I am setting user to 'root' instead of 'deploy' for any eventlistener since at least `memmon` needs write access to supervisord.conf and supervisord.conf.erb sets ownership ot the socket to root with 700 perms.  Seems much better to raise the permissions of eventlisteners than to make open up supervisor more generally to `deploy`.  What do you think?

**Comment by alecpm** [comment]
I think running the memmon, etc. as root is probably the sensible thing to do.  Looks good to me.

**Pull request merged**
