### PR TITLE
Add ability to set up a user with SFTP access

### PR DESCRIPTION
**Pull request by davisagli**

### CODE REVIEW

**Comment by davisagli** [comment]
@alecpm does this look okay to merge?

**Comment by alecpm** [comment]
I'm a little worried about locating the mount dir in /mnt/srv/www.  Do you intend to serve static files out of it or something?  If not, I would suggest locating it in /mnt/shared or another directory not tied to the application webserver data.  I also think it would be more useful if you could add more than a single user, but one is probably adequate for many usecases.

**Comment by alecpm** [comment]
Sorry it took me so long to get to this, it slipped off my radar.  Thanks for implementing it!

**Comment by davisagli** [comment]
Oh huh, I'm not sure why I used /mnt/srv/www. At some point I was aiming to put it somewhere that would be on an EBS volume instead of ephemeral storage so the files don't get lost when the server's rebuilt, but I clearly got turned around.

I suppose it wouldn't be too hard to make it take a list of users, but I'll have to brush up on my ruby.

**Comment by alecpm** [comment]
I generally mount my EBS volumes under /mnt/shared these days (and for simplicity you could generally mount just a single one at that location, though using multiple volumes gives some performance benefits).

**Pull request closed without merging**
